"""Dynamical Lie algebra of the TE-EX ansatz inside the M_z = 0 sector.

Heisenberg exchange conserves both M_z and the total spin S_tot, so the
20-dimensional M_z = 0 sector (binom(6,3) = 20) splits into S_tot blocks of
dimensions 5 + 9 + 5 + 1.  The reachable transformations are therefore at most
SU(5) x SU(9) x SU(5) x U(1), of real dimension (25-1)+(81-1)+(25-1)+1 = 129.

This script computes the Lie algebra actually generated by the five nearest-
neighbour exchange terms {h_12, ..., h_56}: starting from {i h_k} it repeatedly
adds commutators that are linearly independent (over R) of what is already in
the list, until the list stops growing.  It then checks that every element is
block diagonal in the S_tot eigenbasis.

Result: the algebra closes at exactly 129, i.e. the exchange generators alone
already span the whole symmetry-allowed algebra.  Note this is a statement about
arbitrary control of the generator coefficients; whether a *finite* ansatz of L
layers (5L parameters) can approximate a given target is a separate question,
answered numerically by ansatz_expressivity.py.

Appends K_dla to results/results.json.
"""
import json, os
import numpy as np
import torch
from eo_core import get_ops

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'results')
N_SPINS = 6
TOL = 1e-8


def mz0_restriction():
    h_list, sz_ops = get_ops(N_SPINS)
    sz_tot = sum(sz_ops)
    idx = (torch.diagonal(sz_tot).real.abs() < 1e-12).nonzero().squeeze().numpy()
    h_r = [h.numpy()[np.ix_(idx, idx)] for h in h_list]
    return h_r, sz_tot.numpy(), idx


def s_tot_blocks(idx, sz_tot):
    I2 = np.eye(2, dtype=complex)
    X = np.array([[0, 1], [1, 0]], dtype=complex) / 2
    Y = np.array([[0, -1j], [1j, 0]], dtype=complex) / 2

    def kron_list(ms):
        r = ms[0]
        for m in ms[1:]:
            r = np.kron(r, m)
        return r

    sx = sum(kron_list([X if k == i else I2 for k in range(N_SPINS)]) for i in range(N_SPINS))
    sy = sum(kron_list([Y if k == i else I2 for k in range(N_SPINS)]) for i in range(N_SPINS))
    s2 = (sx @ sx + sy @ sy + sz_tot @ sz_tot)[np.ix_(idx, idx)]
    w, V = np.linalg.eigh(s2)
    blocks = [int((np.abs(w - s2v) < 1e-6).sum()) for s2v in (0., 2., 6., 12.)]
    return blocks, V


def generate_algebra(generators, dim):
    rows = np.zeros((0, 2 * dim * dim))
    basis = []

    def add(A):
        nonlocal rows
        v = np.concatenate([A.real.ravel(), A.imag.ravel()])
        nrm = np.linalg.norm(v)
        if nrm < 1e-12:
            return False
        cand = np.vstack([rows, v / nrm])
        if np.linalg.matrix_rank(cand, tol=TOL) > rows.shape[0]:
            rows = cand
            basis.append(A)
            return True
        return False

    for g in generators:
        add(g)
    frontier = list(basis)
    while frontier:
        new = []
        for a in frontier:
            for b in list(basis):
                if add(a @ b - b @ a):
                    new.append(basis[-1])
        frontier = new
    return basis


if __name__ == '__main__':
    h_r, sz_tot, idx = mz0_restriction()
    dim = len(idx)
    blocks, V = s_tot_blocks(idx, sz_tot)
    expected = sum(b * b - 1 for b in blocks) + 1
    print(f'M_z = 0 dimension: {dim} (= binom(6,3))')
    print(f'S_tot block dimensions: {blocks} (sum {sum(blocks)})')
    print(f'dim[su(5)+su(9)+su(5)+u(1)] = {expected}')

    basis = generate_algebra([1j * h for h in h_r], dim)
    print(f'dynamical Lie algebra dimension (real): {len(basis)}')

    block_of = np.concatenate([[i] * b for i, b in enumerate(blocks)])
    off = 0.0
    for A in basis:
        B = V.conj().T @ A @ V
        mask = block_of[:, None] != block_of[None, :]
        off = max(off, float(np.abs(B[mask]).max()))
    print(f'largest off-block matrix element over the whole algebra: {off:.2e}')

    with open(os.path.join(OUT, 'results.json')) as f:
        results = json.load(f)
    results['K_dla'] = {
        'mz0_dim': dim, 's_tot_blocks': blocks,
        'expected_dim_su5_su9_su5_u1': expected,
        'dla_dim': len(basis),
        'max_off_block_element': off,
        'closes_at_symmetry_limit': len(basis) == expected}
    with open(os.path.join(OUT, 'results.json'), 'w') as f:
        json.dump(results, f, indent=2)
